columns:
  - name: order_id
    type: customseq
    datatype: int
    pos: 1
  - name: customer_id
    type: customseq
    datatype: int
    pos: 2
  - name: customer_name
    type: firstname
    datatype: string
    pos: 3
  - name: product_id
    type: customseq
    datatype: int
    pos: 4
  - name: product_name
    type: prodname
    datatype: string
    pos: 5
  - name: product_category
    type: prodcat
    datatype: string
    pos: 6
  - name: payment_type
    type: customlist
    datatype: string
    values: ["Credit Card", "Debit Card", "UPI", "Bank Transfer", "Wallet"]
    pos: 7
  - name: qty
    type: customint
    datatype: int
    start: 1
    end: 100
    pos: 8
  - name: price
    type: customfloat
    datatype: float
    start: 1.00
    end: 3500.00
    precision: 2
    pos: 9
  - name: datetime
    type: customdate
    datatype: datetime
    start: "2015-01-01 00:00:00"
    end: "2024-12-31 23:59:59"
    pos: 10
  - name: country
    type: country
    datatype: string
    countries:
      ["US", "CA", "UK", "DE", "FR", "IT", "ES", "AU", "JP", "BR", "IN", "MX"]
    pos: 11
  - name: city
    type:
    datatype:
    pos: 13
  - name: ecommerce_website_name
    type: website
    datatype: string
    domain: [".com", ".net", ".org", ".edu"]
    pos: 13
  - name: payment_txn_id
    type: customuuid
    datatype: string
    characterlimit: 35
    numeric: True
    pos: 14
  - name: payment_txn_success
    type: customlist
    datatype: string
    values: ["Y", "N"]
    pos: 15
  - name: failure_reason
    type: customlist
    datatype: string
    values:
      [
        "",
        "Insufficient Funds",
        "Card Expired",
        "Invalid UPI ID",
        "Network Error",
        "Other",
      ]
    pos: 16
